name: Check License Header
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  css:

    steps:
    - uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.18.0'
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        go install github.com/google/addlicense@v1.0.0
    - name: Check license headers
      run: |
        set -e

        addlicense -check -l mit -c "OpenLens Authors" src/**/*.?css
